### ISSUE TITLE
Dexter changes the activity lifecycle

### ISSUE THREAD

**Issue by JackLauu** [Karumi/Dexter#106]
### Steps to reproduce
Use Dexter.checkPermission in OnItemClick.onClick. Every click will cause activity onResume called. It will cause adpater populating again and the getView state is not expected.

### Version of the library
2.3.1

**Comment by Serchinastico** [comment]
Hi @JackLauu 

I highly recommend you to start using Dexter 3.x.y, the problem is that the method in Android to know if a permission has been granted or not needs an `Activity` instance. In 2.x.y we were creating our own Activity and that had the ugly side effect of calling the presented activity `onResume` method. In Dexter 3.x.y we are requiring your Activity so that we don't have to start any other activity if no permissions are being requested.

You can read more about it in issue #104 and PR #75.

Hope that makes sense and answers your question.

**Comment by JackLauu** [comment]
That's ok, thank you.
