### ISSUE TITLE
Add ability to style snackbars with light theme, or any other colour theme

### ISSUE THREAD

**Issue by Kisty** [Karumi/Dexter#119]
### Expected behaviour
Snackbar background not dark (light)

### Actual behaviour
Snackbar background dark

### Steps to reproduce
See https://www.github.com/Kisty/Dexter

### Version of the library
2.4,0

**Comment by Serchinastico** [comment]
Hi @Kisty 

First of all, thank you for reporting! 
Sadly, we are not considering improving the snackbar in any way as it is just an implementation so that you can start using the library right away. It is meant to be replaced by your own snackbar (or any other widget) once you get comfortable with the library.

Once again, thank you for your time!
