### ISSUE TITLE
Unable to run sample

### ISSUE THREAD

**Issue by IgorGanapolsky** [Karumi/Dexter#145]
### Expected behaviour
Sample should compile and run in Android Studio

### Actual behaviour
Build error:
> Error:Could not read /Dexter/dexter/build/intermediates/typedefs.txt: /Dexter/dexter/build/intermediates/typedefs.txt (No such file or directory)
Error:java.lang.RuntimeException: Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.

### Steps to reproduce
Import the project in Android Studio 2.4
Try to run the sample
Observe the build error

### Version of the library
Latest

**Comment by pedrovgs** [comment]
Hi @IgorGanapolsky!

I've reviewed the project state and our CI environment is building and testing the app properly as you can see [here](https://travis-ci.org/Karumi/Dexter/branches). The problem you are facing has to be related to a bug in the [Android Studio Preview](https://developer.android.com/studio/preview/index.html). The [latest stable release for Android Studio is 2.3.2](https://developer.android.com/studio/index.html) so I guess your error will be fixed by Android Studio developers soon.
