### ISSUE TITLE
permission declaration inside the application tag does not send any notification as that does not allow app to request the required permissions.

### ISSUE THREAD

**Issue by RbkGh** [Karumi/Dexter#195]
### Expected behaviour
There should be a notification when the permission is declared inside application tag in the manifest file or the docs should be updated to ensure that users of the library do not forget to declare the permissions outside the application tag in the manifest file.

### Actual behaviour
The request for the permission simply does not show up and the permission is not granted.

**Comment by fjfdeztoro** [comment]
Hi @RbkGh, thanks for your request but Dexter's purpose is to handle all the boiler plate related to the permission handling so you can focus in your app business logic.

If you declare your permissions outside the application tag, Dexter will behave as the system, so that's not an issue.

Once said that, if you have a PR that solves the problem you've described, I encourage you to submit it so we can review it and discuss about it.

**Comment by RbkGh** [comment]
#196 this pull request should enhance this
