### ISSUE TITLE
Dexter.java avaliable on gradle is diferent of Dexter.java avaliable on github repository

### ISSUE THREAD

**Issue by jackmiras** [Karumi/Dexter#23]
The class Dexter.java avaliable by gradle doesn't contain the method isRequestOngoing and the class Dexter.java avaliable in the github repository does. Can you guys publish another version of Dexter to use by gradle that contains isRequestOngoing method?

**Comment by pedrovgs** [comment]
Hi @jackmiras we are going to publish a new version this week. We are waiting for a PR review :)

**Comment by Serchinastico** [comment]
Hi @jackmiras 

This will happen from time to time as we are using master for backwards-compatible changes in order to keep the repository simple. We are sorry for the inconveniences this flow might cause but we already discussed it and we think the size of the project is not worth a more complex solution.

Anyways, the latest version has been already released in github and will be available in maven central in a few hours :3

Thank you for your feedback!
