### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by liqian685** [Karumi/Dexter#24]
I detect memory leaks  by the library(https://github.com/square/leakcanary) in my app.It report this https://drive.google.com/open?id=0BzO_M3MAsb-CbFVkQU4tclRrMDg

**Comment by pedrovgs** [comment]
Hi @liqian685 thanks for the issue. We will review this carefully.

**Comment by emmano** [comment]
@liqian685 Are you calling `Dexter.initialize(this)` inside an `Activity`? If so, pass the application `Context` instead of `this`.

I think you might see the leak due to this inside `Dexter.java`:

>private static DexterInstance instance;
  instance = new DexterInstance(context, androidPermissionService, intentProvider);

As you can see, `instance` is a `static` variable, so if you pass this to `Dexter.initialize()` while inside an `Activity`, it will be leaked.

**Comment by pedrovgs** [comment]
Fixed at #25 and already released :)
