### ISSUE TITLE
Saving state of some permission

### ISSUE THREAD

**Issue by TOMKHAN** [Karumi/Dexter#37]
This is probably not a lib issue, but the one of not understanding one and I'm sure some other devs have the same question.

I ask for permission with PermissionListener and override those three methods. What happens in permission denied is up to me. But when I (for example, want to fetch location of the user) and he/she didn't gave the app permission to access FINE_LOCATION, it's up to me to save that permission denied somewhere (SharedPreferences?) and then in that code for fetching, I have to check everytime the state of that permission that I previously saved in (SharedPreferences?)?

My question is then, has the library some in-built mechanism to save if the permission is denied and then with that I can check that some code shouldn't be executed? For the case when permission is given to the app, everything is working fine out of the box.

btw. great lib, helps a lot :) :+1:

**Comment by pedrovgs** [comment]
Hi @TOMKHAN, thanks for your quiestion :) We are not saving the state of every permission in the app because the user can change the value of any permission even if the application is not running. You should always ask for the permission and use the listener mechanism to decide what to do depending on the permissions state.

If the user has denied the permission forever you'll always get a denied permission until the application be reinstalled or the permission be modified from the application settings.

Is this the answer to your question?

**Comment by TOMKHAN** [comment]
Hi @pedrovgs :)
Then with what method call can I check if the permission is already given? Because, if I understand correctly, onPermissionGranted() is called on user accepting the permission.

This bugs me because I have one static method getLocation() that is called 30+ times throughout the project from all types of views (Fragments/Activities) and that method is returning a GPS object, but the app will stop if I block the UI thread with the dialog showing the permission. So I was hoping for some method inside Dexter to return the state of that permission so I can just return null instead of GPS object and then warn the user that he/she hasn't accepted the permission or something like that.

**Comment by pedrovgs** [comment]
``onPerissionGranted()`` is invoked on user accepting the permission or if the user has already accepted the permission.

If the user has already accepted your permission the dialog wont be shown. A similar approach is used with the deny permission execution branch. This is how the new Android Permissions System has been designed. You'll have to move your gps usage to the listener configured to use Dexter or the Androd Permissions system, because until that listener is not invoked you don't know if the user has or not the permission.

**Comment by TOMKHAN** [comment]
It's not written in the docs, so it confused me. Thanks @pedrovgs, you've helped me enough :) 

And once more, good job on the lib :+1:

**Comment by pedrovgs** [comment]
We didn't add this documentation to the README.md because the library usage is similar to the official Android Permission System. But I guess this can be confusing. Thanks for your question and for your time!
