### ISSUE TITLE
Research if it's possible to provide better feedback for perma-denied permissions

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Dexter#4]
We should investigate if it's possible to add a new method in ``PermissionListener`` to notify clients when the user denies a permission and asks Android to never ask him again about it.

**Comment by anothem** [comment]
The only way I know of doing it is by recording (e.g. using a shared preference) if the permission was ever requested before. If it was requested before AND showRationale() returns false, it means it was perma-denied. Recording the previous request is needed because showRationale() returns false both when perma-denied and when the permission was never requested at all. 

It would be easy to add something like this to the library, but there are two issues I can see right away.
1 - All permission requests in the app should be done with the library, otherwise won't work
2 - If permissions were requested before the library was integrated in the app, again this won't work

**Comment by anothem** [comment]
Actually cross that. Since this check would happen in the listener, it means the permission must have been requested at least once before, specifically the request that invoked this very listener. So it might be sufficient to check shouldShowRationale() in the listener, and if false it's perma-denied. 
Need to test this to confirm, but seems like it should work. I'd be glad to look into it and submit a PR

**Comment by Serchinastico** [comment]
@anothem thanks for the insight! I'd add another case: what happens if the user changes the permissions manually through the android settings, will we be able to detect it somehow?

Feel free to send us a PR if you find a clean solution and we will be glad to review it.

**Comment by Serchinastico** [comment]
Merged in master and added to release 2.0.0, thanks again @anothem !

**Comment by anothem** [comment]
No problem, glad to help :)

**Comment by AlexioVay** [comment]
Sorry to reopen this old thread, but how exactly do I check if a permission request has been set to "never ask again" by an user?
