### ISSUE TITLE
Dexter activity seriously limits application capabilities

### ISSUE THREAD

**Issue by indiandragon** [Karumi/Dexter#47]
Greetings Dexter team, 

This issue could be related to issue #45 

I have an Activity (Webview)  which I call from browser with View intent  and  request for permissions through dexter and when I do this opens up the main activity since the DexterActivity class is called as **NEW TASK**. This would be against my application flow and I'm sure that this would affect many.

I'm requesting MultiplePermissions. 

Dexter is an extremely useful framework  and I have integrated it successfully through out my app but due to this issue I have to rework the flow.

**Comment by Serchinastico** [comment]
Hi @indiandragon,

We are aware of the issue. In the meantime, have you tried overriding the `DexterActivity` options from your own `AndroidManifest.xml`? It might solve your specific problem until someone gets a better solution (we kindly remind everyone that PRs are more than welcome :smile: ).

Thanks for reporting and your support.

**Comment by linghp** [comment]
In DexterInstance.java:
  private void startTransparentActivityIfNeeded() {
    Intent intent = intentProvider.get(context, DexterActivity.class);
    intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    context.startActivity(intent);
  }
how to do?
When I need permission in application,but my project flow is WelcomeActivity,MainActivity. So,DexterActivity is invisible.Now,Activity stack order is DexterActivity ,MainActivity.
Currently is MainActivity.Can't see DexterActivity.How do you think?

**Comment by danipl** [comment]
I think this is bothering me too, my application works with a set of fragments over one main activity, this activity doesn't change never, but when I call any Dexter methods to check permissions, the onPause() method on my activity is being called, releasing a lot of resources and crashing my app. If I handle permissions by myself without Dexter everything works fine.

**Comment by Serchinastico** [comment]
Hi,

One of the ideas behind Dexter is to decouple your activities from the permissions request flow. That's why the library creates an activity of its own. We are not planning to change that behaviour, if that limits your app I'd rather recommend using other library or just handling the permissions by yourself.

Got to say though that if you have problems when your activity is being paused... you will probably have them whether you keep using Dexter or not because the native request permission activity is going to pause yours anyways.

We still have to take a look at the new task configuration so I'll keep the issue open.

Thanks for your time and your feedback.
