### ISSUE TITLE
Create in-depth acceptance tests

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Dexter#49]
As the library is getting bigger we need acceptance tests to verify all the cases we are handling.
Playing around with permissions in UI tests is usually a bad idea but this project is probably the best to do it anyways.
Do some research to run one test at a time (probably with Spoon) and reset device permissions before the execution of each test. It will be slow as hell but probably better than nothing.

**Comment by Serchinastico** [comment]
Closed due to impracticality of the task, running acceptance tests with spoon, one at a time is too slow, having the Android behaviour simulated in a mock should be good enough for our needs.

**Comment by pedrovgs** [comment]
Can we use a similar approach to the one shown in [this screencast](https://www.youtube.com/watch?v=U5YZcq557gA&feature=youtu.be&utm_source=Android+Weekly&utm_campaign=f7b91895ba-Android_Weekly_205&utm_medium=email&utm_term=0_4eb677ad19-f7b91895ba-337845529)?  Instead of execute the command from a gradle task executing the command from the test code. Thoughts?
