### ISSUE TITLE
Dialog not showing up after firts "Deny"

### ISSUE THREAD

**Issue by Mariovc** [Karumi/Dexter#57]
### Expected behaviour
Show a default `Dialog` when requesting a permission after the first "Deny"

### Actual behaviour
Nothing appears

### Steps to reproduce
1. Request permission
2. Deny permission
3. Request again permission

### Version of the library
2.2.2

### Code
It only happens when I use the default `dialogPermissionListener`:

    DialogOnDeniedPermissionListener.Builder
        .withContext(context)
        .withTitle("Camera permission")
        .withMessage("Camera permission is needed to take pictures of your cat")
        .withButtonText(android.R.string.ok)
        .withIcon(R.mipmap.my_icon)
        .build();

Using this sample code:

    PermissionListener snackbarPermissionListener =
                    SnackbarOnDeniedPermissionListener.Builder
                            .with(rootView, "Camera access is needed to take pictures of your dog")
                            .withOpenSettingsButton("Settings")
                            .build();
            Dexter.checkPermission(
                    new CompositePermissionListener(snackbarPermissionListener, dialogPermissionListener),
                    Manifest.permission.CAMERA
            );

**Comment by Serchinastico** [comment]
Hi @Mariovc 

I think I know what's happening, the default `DialogOnDeniedPermissionListener` implementation doesn't handle the `onPermissionRationaleShouldBeShown` callback, letting implementers override it. That means that the second time a permission is requested Android gives you the opportunity to show a rationale to explain why your app needs the requested permission and we aren't returning anything.

We should make it more clear for clients that default implementations are meant to be overridden (maybe turning them into abstract classes) or composed with other listeners to handle that scenario.

We need to think if that's a behaviour we want to preserve or change in order to avoid this misunderstandings.

**Comment by Mariovc** [comment]
I'd rather to show a rationale by default. I think it is a better behaviour because it is what most people expect from it. If the client creates a default `DialogOnDeniedPermissionListener` and nothing happens, it seems to be that something is wrong instead of thinking it was made deliberately.

But it is open to discuss.
Thanks

**Comment by Serchinastico** [comment]
Sounds like the right thing to do to me too, @pedrovgs @flipper83 thoughts?

**Comment by pedrovgs** [comment]
Yeap, it sounds like the right thing to do :)
