### ISSUE TITLE
Ability to check if PermissionToken is already resolved?

### ISSUE THREAD

**Issue by Trikke** [Karumi/Dexter#93]
### Question

To be able to check if the token is already resolved. In some custom scenario's this can be helpful.
### Problem

If i create an Alertdialog to show a Rationale (like in your Sample in the SampleActivity), there is a listener for the negative button, positive button and dialog dismissal. These will call the given token to do something with the request.
The problem is that if you use either buttons, the dismiss listener will also be called. For the token itself, this is no issue to be called twice because there's some internal checking if it is already resolved or not.
My own issue is that i use **shownPermissionRationaleDialog** elsewhere in my code to check some stuff. But because the dismiss listener is always called, this value will always be true.

``` java
AlertDialog alertDialog = new AlertDialog.Builder(context).setTitle(title)
                        .setMessage(message)
                        .setNegativeButton(android.R.string.cancel, new DialogInterface.OnClickListener() {
                            @Override public void onClick(DialogInterface dialog, int which) {
                                shownPermissionRationaleDialog = true;
                                dialog.dismiss();
                                token.cancelPermissionRequest();
                            }
                        })
                        .setPositiveButton(android.R.string.ok, new DialogInterface.OnClickListener() {
                            @Override public void onClick(DialogInterface dialog, int which) {
                                shownPermissionRationaleDialog = false;
                                dialog.dismiss();
                                token.continuePermissionRequest();
                            }
                        })
                        .create();
                alertDialog.setOnDismissListener(new DialogInterface.OnDismissListener() {
                    @Override public void onDismiss(DialogInterface dialogInterface) {
                        token.cancelPermissionRequest();
                        shownPermissionRationaleDialog = true;
                    }
                });
                alertDialog.show();
```
### Steps to reproduce

Create above dialog when showing a rationele with a token.
### Version of the library

latest version

**Comment by Serchinastico** [comment]
Hi @Trikke,

Sorry for the late response. I'm reading your issue and I'm wondering if that's something that has to be solved from Dexter itself. Basically, I'd like to keep its API as simple as possible and I don't like the idea of adding methods to mitigate an issue in a very specific scenario.

I'd recommend you to use another boolean value to know if the user has actively dismissed or accepted the alert by clicking one of its buttons. That or create an enum with these possible values (`NONE`, `OK_PRESSED`, `CANCEL_PRESSED` and `DISMISSED`) so that you can know if the user did something else before dismissing the dialog.

Thanks for reporting but I don't think Dexter should be handling this.
