### ISSUE TITLE
Possible memory leak on Dexter

### ISSUE THREAD

**Issue by rocboronat** [Karumi/Dexter#94]
Hi team!

We're having a small memory leak using Dexter. We noticed it thanks to Leak Canary.

Do you have any idea of fixing it? Probably we are just doing a bad use of Dexter :·)

BTW, we're using Dexter 2.2.2

Thanks!

![screenshot_20161025-172407](https://cloud.githubusercontent.com/assets/456499/19694930/720714a4-9ae1-11e6-92c8-67c3b48033e3.png)

**Comment by Serchinastico** [comment]
Hi @rocboronat 

We will take a look and try to give you a response soon.

Thanks for reporting!

**Comment by bleuf1shi** [comment]
I just encountered the same issue a few days ago. I wrote a fix and have been using it. I'll make a pull request.

**Comment by bleuf1shi** [comment]
link to pull request. https://github.com/Karumi/Dexter/pull/101

**Comment by bleuf1shi** [comment]
@Serchinastico  , my pull request is failing CI tests because of something unrelated.

**Comment by Serchinastico** [comment]
Hello everyone,

I'm trying to track the memory leak and I think the problem is that either the Android permission dialog or the Dexter activity is being displayed, leaving your activity behind. It's normal that LeakCanary is reporting that as a memory leak because, strictly speaking, it is a memory leak. However, given how Dexter is designed it is not possible to avoid it. We are leaking the listener (and most of the time, by extension the activity) on purpose so that you don't need to register to the Android framework, Android can recreate activities and sends them the permissions response in one of its methods, we can't. With that said, the leak is temporal, we are not holding a reference to the activity forever, we only hold it while we need it, that is, while we still have something to notify back to the listener.

Honestly, the only way to fix this would be to store an instance of `DexterInstance` in the calling activity and store a `WeakReference` to the activity somehow. I don't see how that can be achieved from within the library. If you are still concerned about it, you can always call Dexter from a class holding a weak reference to the activity (a presenter, a view model or whatever other class you are using in your architecture to abstract things away from the framework).

Thank you very much reporting but I'm afraid there is nothing we can do to address the issue.

**Comment by rocboronat** [comment]
Hi @Serchinastico! Thanks for this extended answer: it's an easy way to know how Dexter works. And thanks for your work, too! 😊
